#!/bin/bash

# anaconda
	echo -e "[+] source anaconda env."
	source anaconda.env-20190430

# create
	conda create --name python35 python=3.5

	source activate python35
	python --version

	source deactivate python35
	python --version

	conda remove --name python35 --all

# check env.
	conda info -e

# make caffe
	sudo make pycaffe
	sudo make runtest -j8

# jupyter notebook

	# issue: importerror: cannot import name path
	sudo pip install ipython --upgrade --proxy="http://child-prc.intel.com:913"
	sudo pip install "ipython[noteboook]" --upgrade --proxy="http://child-prc.intel.com:913"
	pip install protobuf

	# re-enter shell
	jupyter-notebook
