FROM ubuntu:bionic

#ARG DEBIAN_FRONTEND=noninteractive
#ENV http_proxy 'http://child-prc.intel.com:913'
#ENV https_proxy 'http://child-prc.intel.com:913'
#ENV http_proxy ""
#ENV https_proxy ""

#RUN apt-get -q -y update \
#        && apt-get install -y gcc 
#build-essential

COPY src/ /uevent_dump/src

#CMD ls -l /

#ENTRYPOINT ["/uevent_dumper"]
#ENTRYPOINT ["/uevent_dump/src/uevent_dump.sh"]

